version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  app:
    image: docker-node-express-mongoapp
    container_name: app
    build: .
    command: node server.js
    ports:
      - "3000:3000"
    links:
      - mongo
volumes:
  mongodata: